[2023-01-01 03:01:09,909] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_example.model.my_project.my_first_dbt_model manual__2023-01-01T11:01:07.880959+00:00 [queued]>
[2023-01-01 03:01:09,914] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_example.model.my_project.my_first_dbt_model manual__2023-01-01T11:01:07.880959+00:00 [queued]>
[2023-01-01 03:01:09,914] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-01 03:01:09,914] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-01 03:01:09,914] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-01 03:01:09,922] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): model.my_project.my_first_dbt_model> on 2023-01-01 11:01:07.880959+00:00
[2023-01-01 03:01:09,924] {standard_task_runner.py:52} INFO - Started process 3079 to run task
[2023-01-01 03:01:09,928] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_example', 'model.my_project.my_first_dbt_model', 'manual__2023-01-01T11:01:07.880959+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dbt_example.py', '--cfg-path', '/var/folders/7s/852sy8qx6lx4d2xxm8yv15sw0000gn/T/tmpc_nefw7a', '--error-file', '/var/folders/7s/852sy8qx6lx4d2xxm8yv15sw0000gn/T/tmp6onz80z4']
[2023-01-01 03:01:09,929] {standard_task_runner.py:80} INFO - Job 40: Subtask model.my_project.my_first_dbt_model
[2023-01-01 03:01:09,967] {task_command.py:370} INFO - Running <TaskInstance: dbt_example.model.my_project.my_first_dbt_model manual__2023-01-01T11:01:07.880959+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-01-01 03:01:10,007] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_example
AIRFLOW_CTX_TASK_ID=model.my_project.my_first_dbt_model
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T11:01:07.880959+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-01T11:01:07.880959+00:00
[2023-01-01 03:01:10,008] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/7s/852sy8qx6lx4d2xxm8yv15sw0000gn/T
[2023-01-01 03:01:10,009] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /Users/kayleeyvo/Documents/DS_Learning/datafold_project/repos/demo/dbt/my_project && eval "\\$(pyenv init -)" && eval "\\$(pyenv virtualenv-init -)" && pyenv activate demo_dbt && dbt run --models my_first_dbt_model']
[2023-01-01 03:01:10,014] {subprocess.py:85} INFO - Output:
[2023-01-01 03:01:10,070] {subprocess.py:92} INFO - bash: PATH="$(bash: command not found
[2023-01-01 03:01:10,070] {subprocess.py:96} INFO - Command exited with return code 127
[2023-01-01 03:01:10,078] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/kayleeyvo/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-01 03:01:10,082] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt_example, task_id=model.my_project.my_first_dbt_model, execution_date=20230101T110107, start_date=20230101T110109, end_date=20230101T110110
[2023-01-01 03:01:10,089] {standard_task_runner.py:92} ERROR - Failed to execute job 40 for task model.my_project.my_first_dbt_model (Bash command failed. The command returned a non-zero exit code 127.; 3079)
[2023-01-01 03:01:10,107] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-01 03:01:10,154] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
